import 'package:flutter/material.dart';
import '../core/api.dart';
import '../core/theme.dart';
class AdminShell extends StatefulWidget {const AdminShell({super.key,required this.api,required this.user,required this.onSignOut});final BikeApi api;final Map<String,dynamic> user;final Future<void> Function() onSignOut;@override State<AdminShell> createState()=>_AdminShellState();}
class _AdminShellState extends State<AdminShell>{List<dynamic> mechanics=[],rescues=[];String? error;@override void initState(){super.initState();refresh();}Future<void> refresh()async{try{final m=await widget.api.call('GET','/admin/mechanics'),r=await widget.api.call('GET','/admin/rescues');if(mounted)setState((){mechanics=m as List;rescues=r as List;error=null;});}catch(e){if(mounted)setState(()=>error=e.toString());}}
 Future<void> verify(String id,String status)async{try{await widget.api.call('PATCH','/admin/mechanics/$id/verification',data:{'status':status});await refresh();}catch(e){if(mounted)setState(()=>error=e.toString());}}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Bike Rescue · Admin'),actions:[IconButton(onPressed:refresh,icon:const Icon(Icons.refresh)),IconButton(onPressed:widget.onSignOut,icon:const Icon(Icons.logout))]),body:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:980),child:ListView(padding:const EdgeInsets.all(22),children:[const BikeLogo(size:36),const SizedBox(height:16),Text('Operations overview',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:18),Wrap(spacing:12,runSpacing:12,children:[_Metric(label:'Active rescues',value:'${rescues.where((r)=>!['COMPLETED','CANCELLED'].contains(r['status'])).length}',icon:Icons.route),_Metric(label:'Pending verification',value:'${mechanics.where((m)=>m['verification']=='PENDING').length}',icon:Icons.verified_user_outlined),_Metric(label:'Online mechanics',value:'${mechanics.where((m)=>m['online']==true).length}',icon:Icons.two_wheeler)]),if(error!=null)Padding(padding:const EdgeInsets.all(12),child:Text(error!,style:const TextStyle(color:Colors.red))),const SizedBox(height:28),const Text('Mechanic verification',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:12),if(mechanics.isEmpty)const SectionCard(child:Text('No mechanics registered.')),for(final m in mechanics)Padding(padding:const EdgeInsets.only(bottom:10),child:SectionCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(m['full_name']?.toString().isNotEmpty==true?m['full_name'].toString():m['phone'].toString(),style:const TextStyle(fontWeight:FontWeight.bold)),Text('Status: ${m['verification']} · Skills: ${(m['skills'] as List).join(', ')}'),const SizedBox(height:10),Wrap(spacing:8,children:[OutlinedButton(onPressed:()=>verify(m['user_id'].toString(),'REJECTED'),child:const Text('Reject')),FilledButton(onPressed:()=>verify(m['user_id'].toString(),'VERIFIED'),child:const Text('Verify')),TextButton(onPressed:()=>verify(m['user_id'].toString(),'SUSPENDED'),child:const Text('Suspend'))])]))),const SizedBox(height:20),const Text('Recent rescues',style:TextStyle(fontSize:19,fontWeight:FontWeight.bold)),const SizedBox(height:10),if(rescues.isEmpty)const SectionCard(child:Text('No rescues yet.')),for(final r in rescues)Padding(padding:const EdgeInsets.only(bottom:9),child:SectionCard(child:ListTile(contentPadding:EdgeInsets.zero,title:Text(r['issue'].toString()),subtitle:Text(r['status'].toString()),leading:const Icon(Icons.sos,color:orange))))]))));}
}
class _Metric extends StatelessWidget{const _Metric({required this.label,required this.value,required this.icon});final String label,value;final IconData icon;@override Widget build(BuildContext context)=>SizedBox(width:220,child:SectionCard(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(icon,color:orange),const SizedBox(height:13),Text(value,style:const TextStyle(fontSize:27,fontWeight:FontWeight.bold)),Text(label)])));}
