import 'package:flutter/material.dart';
import '../core/api.dart';
import '../core/theme.dart';
class AuthScreen extends StatefulWidget {const AuthScreen({super.key,required this.api,required this.onSignedIn});final BikeApi api;final ValueChanged<Map<String,dynamic>> onSignedIn;@override State<AuthScreen> createState()=>_AuthScreenState();}
class _AuthScreenState extends State<AuthScreen>{final phone=TextEditingController(),code=TextEditingController();bool sent=false,busy=false;String role='RIDER';String? error;
 @override void dispose(){phone.dispose();code.dispose();super.dispose();}
 Future<void> submit()async{setState((){busy=true;error=null;});try{if(!sent){await widget.api.call('POST','/auth/send-otp',data:{'phone':phone.text.trim()});if(mounted)setState(()=>sent=true);}else{final result=Map<String,dynamic>.from(await widget.api.call('POST','/auth/verify-otp',data:{'phone':phone.text.trim(),'code':code.text.trim(),'role':role}));await widget.api.saveToken(result['token'].toString());widget.onSignedIn(Map<String,dynamic>.from(result['user']));}}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
 @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:440),child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const BikeLogo(size:46),const SizedBox(height:35),Text('Help for every ride.',style:Theme.of(context).textTheme.headlineMedium),const SizedBox(height:10),const Text('Sign in to request roadside support or assist nearby riders.'),const SizedBox(height:35),SectionCard(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Text('Continue with your phone',style:TextStyle(fontWeight:FontWeight.bold,fontSize:17)),const SizedBox(height:17),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'10-digit mobile number'),enabled:!sent),if(!sent)...[const SizedBox(height:12),DropdownButtonFormField<String>(initialValue:role,decoration:const InputDecoration(labelText:'I am a'),items:const [DropdownMenuItem(value:'RIDER',child:Text('Rider')),DropdownMenuItem(value:'MECHANIC',child:Text('Mechanic partner'))],onChanged:(v)=>setState(()=>role=v??role))],if(sent)...[const SizedBox(height:12),TextField(controller:code,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'6-digit OTP'))],if(error!=null)...[const SizedBox(height:12),Text(error!,style:const TextStyle(color:Colors.red))],const SizedBox(height:18),FilledButton(onPressed:busy?null:submit,child:Text(busy?'Please wait...':sent?'Verify and continue':'Send OTP')),if(sent)TextButton(onPressed:busy?null:()=>setState(()=>sent=false),child:const Text('Change phone number'))])),const SizedBox(height:20),const Text('Local setup: OTP appears in your API terminal. A delivery provider is required before production.',style:TextStyle(color:Colors.black54,fontSize:12))]))))));}
}
